dependencies {
    implementation("org.apache.flink:flink-shaded-guava:18.0-7.0")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-core"))
    testImplementation("org.apache.flink:flink-shaded-hadoop-2:2.4.1-7.0")
    testImplementation("org.apache.flink:flink-shaded-jackson:2.9.8-7.0")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-optimizer"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-runtime-web"))
    testImplementation(project(":flink-runtime-web"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-scala"))
    testImplementation(project(":flink-scala"))
    testImplementation(project(":flink-test-utils-parent:flink-test-utils-junit"))
    testImplementation(project(":flink-test-utils-parent:flink-test-utils"))
    testImplementation(project(":flink-examples:flink-examples-batch"))
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-connectors:flink-hadoop-compatibility"))
    testImplementation(project(":flink-connectors:flink-hadoop-compatibility"))
    testImplementation(project(":flink-optimizer"))
    testImplementation(project(":flink-runtime"))
    testImplementation("org.apache.curator:curator-test:2.12.0")
    testImplementation("org.scalatest:scalatest:3.0.0")
    testImplementation("com.typesafe.akka:akka-testkit:2.5.21")
    testImplementation("joda-time:joda-time:2.5")
    testImplementation("org.joda:joda-convert:1.7")
    testImplementation(project(":flink-state-backends:flink-statebackend-rocksdb"))
    testImplementation("com.github.oshi:oshi-core:3.4.0")
    testImplementation("org.reflections:reflections:0.9.10")
}

description = "flink-tests"
