dependencies {
    implementation(Libs.flink_shaded_guava)
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-core"))
    testImplementation(Libs.flink_shaded_hadoop_2)
    testImplementation(Libs.flink_shaded_jackson)
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-optimizer"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-runtime-web"))
    testImplementation(project(":flink-runtime-web"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-scala"))
    testImplementation(project(":flink-scala"))
    testImplementation(project(":flink-test-utils-parent:flink-test-utils-junit"))
    testImplementation(project(":flink-test-utils-parent:flink-test-utils"))
    testImplementation(project(":flink-examples:flink-examples-batch"))
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-connectors:flink-hadoop-compatibility"))
    testImplementation(project(":flink-connectors:flink-hadoop-compatibility"))
    testImplementation(project(":flink-optimizer"))
    testImplementation(project(":flink-runtime"))
    testImplementation(Libs.curator_test)
    testImplementation(Libs.scalatest_2_11)
    testImplementation(Libs.akka_testkit_2_11)
    testImplementation(Libs.joda_time)
    testImplementation(Libs.joda_convert)
    testImplementation(project(":flink-state-backends:flink-statebackend-rocksdb"))
    testImplementation(Libs.oshi_core)
    testImplementation(Libs.reflections)
}

description = "flink-tests"
