dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-scala"))
    implementation(project(":flink-table:flink-table-common"))
    implementation(project(":flink-table:flink-table-api-java"))
    implementation(project(":flink-table:flink-table-api-java-bridge"))
    implementation(project(":flink-table:flink-table-planner"))
    implementation(project(":flink-table:flink-table-planner-blink"))
    implementation(project(":flink-table:flink-table-runtime-blink"))
    implementation(Libs.jline_terminal)
    implementation(Libs.jline_reader)
    implementation(Libs.flink_shaded_jackson)
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils-parent:flink-test-utils"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-connectors:flink-connector-hive"))
    testImplementation(project(":flink-connectors:flink-hadoop-compatibility"))
    testImplementation(Libs.hive_metastore)
    testImplementation(Libs.hive_exec)
    testImplementation(Libs.hadoop_common)
    compileOnly(project(":flink-connectors:flink-connector-hive"))
    compileOnly(Libs.hadoop_mapreduce_client_core)
}

description = "flink-sql-client"
