import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://github.com/sgroschupf/zkclient
   */
  const val zkclient: String = "com.101tec:zkclient:" + Versions.zkclient

  /**
   * http://www.aliyun.com/product/oss
   */
  const val aliyun_sdk_oss: String = "com.aliyun.oss:aliyun-sdk-oss:" + Versions.aliyun_sdk_oss

  /**
   * https://aws.amazon.com/sdkforjava
   */
  const val aws_java_sdk_core: String = "com.amazonaws:aws-java-sdk-core:" +
      Versions.aws_java_sdk_core

  /**
   * https://aws.amazon.com/sdkforjava
   */
  const val aws_java_sdk_dynamodb: String = "com.amazonaws:aws-java-sdk-dynamodb:" +
      Versions.aws_java_sdk_dynamodb

  /**
   * https://aws.amazon.com/sdkforjava
   */
  const val aws_java_sdk_kms: String = "com.amazonaws:aws-java-sdk-kms:" + Versions.aws_java_sdk_kms

  /**
   * https://aws.amazon.com/sdkforjava
   */
  const val aws_java_sdk_s3: String = "com.amazonaws:aws-java-sdk-s3:" + Versions.aws_java_sdk_s3

  /**
   * https://github.com/dataArtisans/frocksdb
   */
  const val frocksdbjni: String = "com.data-artisans:frocksdbjni:" + Versions.frocksdbjni

  /**
   * https://github.com/datastax/java-driver
   */
  const val cassandra_driver_core: String = "com.datastax.cassandra:cassandra-driver-core:" +
      Versions.com_datastax_cassandra

  /**
   * https://github.com/datastax/java-driver
   */
  const val cassandra_driver_mapping: String = "com.datastax.cassandra:cassandra-driver-mapping:" +
      Versions.com_datastax_cassandra

  /**
   * https://github.com/EsotericSoftware/kryo
   */
  const val kryo: String = "com.esotericsoftware.kryo:kryo:" + Versions.kryo

  /**
   * https://github.com/facebook/presto-hadoop-apache2
   */
  const val hadoop_apache2: String = "com.facebook.presto.hadoop:hadoop-apache2:" +
      Versions.hadoop_apache2

  /**
   * https://github.com/facebook/presto
   */
  const val presto_hive: String = "com.facebook.presto:presto-hive:" + Versions.presto_hive

  /**
   * https://github.com/oshi/oshi
   */
  const val oshi_core: String = "com.github.oshi:oshi-core:" + Versions.oshi_core

  /**
   * https://github.com/scopt/scopt
   */
  const val scopt_2_11: String = "com.github.scopt:scopt_2.11:" + Versions.scopt_2_11

  /**
   * http://wiremock.org
   */
  const val wiremock: String = "com.github.tomakehurst:wiremock:" + Versions.wiremock

  /**
   * https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-pubsub
   */
  const val google_cloud_pubsub: String = "com.google.cloud:google-cloud-pubsub:" +
      Versions.google_cloud_pubsub

  /**
   * http://findbugs.sourceforge.net/
   */
  const val jsr305: String = "com.google.code.findbugs:jsr305:" + Versions.jsr305

  /**
   * https://github.com/google/guava
   */
  const val guava: String = "com.google.guava:guava:" + Versions.guava

  /**
   * https://github.com/klarna/HiveRunner
   */
  const val hiverunner: String = "com.klarna:hiverunner:" + Versions.hiverunner

  /**
   * http://unirest.io/
   */
  const val unirest_java: String = "com.mashape.unirest:unirest-java:" + Versions.unirest_java

  /**
   * https://github.com/Azure/azure-sdk-for-java
   */
  const val azure: String = "com.microsoft.azure:azure:" + Versions.azure

  /**
   * https://github.com/Netflix/Fenzo
   */
  const val fenzo_core: String = "com.netflix.fenzo:fenzo-core:" + Versions.fenzo_core

  /**
   * https://www.rabbitmq.com
   */
  const val amqp_client: String = "com.rabbitmq:amqp-client:" + Versions.amqp_client

  /**
   * https://github.com/spotify/docker-client
   */
  const val docker_client: String = "com.spotify:docker-client:" + Versions.docker_client

  /**
   * https://github.com/square/okhttp
   */
  const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

  const val chill2_11: String = "com.twitter:chill2.11:" + Versions.chill2_11

  /**
   * https://github.com/twitter/chill
   */
  const val chill_2_11: String = "com.twitter:chill_2.11:" + Versions.chill_2_11

  /**
   * http://github.com/twitter/hbc
   */
  const val hbc_core: String = "com.twitter:hbc-core:" + Versions.hbc_core

  /**
   * https://akka.io/
   */
  const val akka_actor_2_11: String = "com.typesafe.akka:akka-actor_2.11:" +
      Versions.com_typesafe_akka

  /**
   * https://akka.io/
   */
  const val akka_protobuf_2_11: String = "com.typesafe.akka:akka-protobuf_2.11:" +
      Versions.com_typesafe_akka

  /**
   * https://akka.io/
   */
  const val akka_remote_2_11: String = "com.typesafe.akka:akka-remote_2.11:" +
      Versions.com_typesafe_akka

  /**
   * https://akka.io/
   */
  const val akka_slf4j_2_11: String = "com.typesafe.akka:akka-slf4j_2.11:" +
      Versions.com_typesafe_akka

  /**
   * https://akka.io/
   */
  const val akka_stream_2_11: String = "com.typesafe.akka:akka-stream_2.11:" +
      Versions.com_typesafe_akka

  const val akka_testkit: String = "com.typesafe.akka:akka-testkit:" + Versions.com_typesafe_akka

  /**
   * https://akka.io/
   */
  const val akka_testkit_2_11: String = "com.typesafe.akka:akka-testkit_2.11:" +
      Versions.com_typesafe_akka

  /**
   * http://commons.apache.org/proper/commons-cli/
   */
  const val commons_cli: String = "commons-cli:commons-cli:" + Versions.commons_cli

  const val commons_collections: String = "commons-collections:commons-collections:" +
      Versions.commons_collections

  /**
   * http://commons.apache.org/proper/commons-io/
   */
  const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://github.com/airlift/tpch
   */
  const val tpch: String = "io.airlift.tpch:tpch:" + Versions.tpch

  /**
   * http://confluent.io
   */
  const val kafka_schema_registry_client: String = "io.confluent:kafka-schema-registry-client:" +
      Versions.kafka_schema_registry_client

  /**
   * http://metrics.dropwizard.io
   */
  const val metrics_core: String = "io.dropwizard.metrics:metrics-core:" +
      Versions.io_dropwizard_metrics

  /**
   * http://metrics.dropwizard.io
   */
  const val metrics_graphite: String = "io.dropwizard.metrics:metrics-graphite:" +
      Versions.io_dropwizard_metrics

  /**
   * http://netty.io/
   */
  const val netty: String = "io.netty:netty:" + Versions.netty

  /**
   * http://github.com/prometheus/client_java
   */
  const val simpleclient: String = "io.prometheus:simpleclient:" + Versions.io_prometheus

  /**
   * http://github.com/prometheus/client_java
   */
  const val simpleclient_httpserver: String = "io.prometheus:simpleclient_httpserver:" +
      Versions.io_prometheus

  /**
   * http://github.com/prometheus/client_java
   */
  const val simpleclient_pushgateway: String = "io.prometheus:simpleclient_pushgateway:" +
      Versions.io_prometheus

  /**
   * http://fastutil.di.unimi.it/
   */
  const val fastutil: String = "it.unimi.dsi:fastutil:" + Versions.fastutil

  /**
   * https://www.joda.org/joda-time/
   */
  const val joda_time: String = "joda-time:joda-time:" + Versions.joda_time

  /**
   * http://junit.org
   */
  const val junit: String = "junit:junit:" + Versions.junit

  /**
   * http://logging.apache.org/log4j/1.2/
   */
  const val log4j: String = "log4j:log4j:" + Versions.log4j

  /**
   * https://github.com/irmen/Pyrolite
   */
  const val pyrolite: String = "net.razorvine:pyrolite:" + Versions.pyrolite

  const val py4j: String = "net.sf.py4j:py4j:" + Versions.py4j

  /**
   * http://avro.apache.org
   */
  const val avro: String = "org.apache.avro:avro:" + Versions.avro

  /**
   * https://calcite.apache.org/avatica
   */
  const val avatica_core: String = "org.apache.calcite.avatica:avatica-core:" +
      Versions.avatica_core

  /**
   * https://calcite.apache.org
   */
  const val calcite_core: String = "org.apache.calcite:calcite-core:" + Versions.calcite_core

  /**
   * http://cassandra.apache.org
   */
  const val cassandra_all: String = "org.apache.cassandra:cassandra-all:" + Versions.cassandra_all

  /**
   * https://commons.apache.org/proper/commons-compress/
   */
  const val commons_compress: String = "org.apache.commons:commons-compress:" +
      Versions.commons_compress

  /**
   * http://commons.apache.org/proper/commons-lang/
   */
  const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

  /**
   * http://commons.apache.org/proper/commons-math/
   */
  const val commons_math3: String = "org.apache.commons:commons-math3:" + Versions.commons_math3

  /**
   * http://curator.apache.org
   */
  const val curator_recipes: String = "org.apache.curator:curator-recipes:" +
      Versions.org_apache_curator

  /**
   * http://curator.apache.org
   */
  const val curator_test: String = "org.apache.curator:curator-test:" + Versions.org_apache_curator

  /**
   * http://db.apache.org/derby/
   */
  const val derby: String = "org.apache.derby:derby:" + Versions.derby

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_asm_6: String = "org.apache.flink:flink-shaded-asm-6:" +
      Versions.flink_shaded_asm_6

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_guava: String = "org.apache.flink:flink-shaded-guava:" +
      Versions.flink_shaded_guava

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_hadoop_2: String = "org.apache.flink:flink-shaded-hadoop-2:" +
      Versions.flink_shaded_hadoop_2

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_jackson_module_jsonschema: String =
      "org.apache.flink:flink-shaded-jackson-module-jsonSchema:" +
      Versions.flink_shaded_jackson_module_jsonschema

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_jackson: String = "org.apache.flink:flink-shaded-jackson:" +
      Versions.flink_shaded_jackson

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_netty_tcnative_dynamic: String =
      "org.apache.flink:flink-shaded-netty-tcnative-dynamic:" +
      Versions.flink_shaded_netty_tcnative_dynamic

  /**
   * http://flink.apache.org
   */
  const val flink_shaded_netty: String = "org.apache.flink:flink-shaded-netty:" +
      Versions.flink_shaded_netty

  const val hadoop_aliyun: String = "org.apache.hadoop:hadoop-aliyun:" + Versions.hadoop_aliyun

  const val hadoop_aws: String = "org.apache.hadoop:hadoop-aws:" + Versions.hadoop_aws

  const val hadoop_azure: String = "org.apache.hadoop:hadoop-azure:" + Versions.hadoop_azure

  const val hadoop_client: String = "org.apache.hadoop:hadoop-client:" + Versions.hadoop_client

  const val hadoop_common: String = "org.apache.hadoop:hadoop-common:" + Versions.hadoop_common

  const val hadoop_hdfs: String = "org.apache.hadoop:hadoop-hdfs:" + Versions.hadoop_hdfs

  const val hadoop_mapreduce_client_core: String =
      "org.apache.hadoop:hadoop-mapreduce-client-core:" + Versions.hadoop_mapreduce_client_core

  const val hadoop_minicluster: String = "org.apache.hadoop:hadoop-minicluster:" +
      Versions.hadoop_minicluster

  const val hadoop_minikdc: String = "org.apache.hadoop:hadoop-minikdc:" + Versions.hadoop_minikdc

  const val hadoop_openstack: String = "org.apache.hadoop:hadoop-openstack:" +
      Versions.hadoop_openstack

  const val hadoop_yarn_: String = "org.apache.hadoop:hadoop-yarn-:" + Versions.hadoop_yarn_

  const val hadoop_yarn_client: String = "org.apache.hadoop:hadoop-yarn-client:" +
      Versions.hadoop_yarn_client

  /**
   * https://hbase.apache.org
   */
  const val hbase_hadoop_compat: String = "org.apache.hbase:hbase-hadoop-compat:" +
      Versions.org_apache_hbase

  /**
   * https://hbase.apache.org
   */
  const val hbase_hadoop2_compat: String = "org.apache.hbase:hbase-hadoop2-compat:" +
      Versions.org_apache_hbase

  /**
   * https://hbase.apache.org
   */
  const val hbase_server: String = "org.apache.hbase:hbase-server:" + Versions.org_apache_hbase

  /**
   * http://maven.apache.org
   */
  const val hcatalog_core: String = "org.apache.hive.hcatalog:hcatalog-core:" +
      Versions.hcatalog_core

  /**
   * http://hive.apache.org
   */
  const val hive_hcatalog_core: String = "org.apache.hive.hcatalog:hive-hcatalog-core:" +
      Versions.hive_hcatalog_core

  /**
   * http://hive.apache.org
   */
  const val hive_exec: String = "org.apache.hive:hive-exec:" + Versions.org_apache_hive

  /**
   * http://hive.apache.org
   */
  const val hive_metastore: String = "org.apache.hive:hive-metastore:" + Versions.org_apache_hive

  /**
   * http://hive.apache.org
   */
  const val hive_service: String = "org.apache.hive:hive-service:" + Versions.org_apache_hive

  /**
   * https://kafka.apache.org
   */
  const val kafka_clients: String = "org.apache.kafka:kafka-clients:" + Versions.kafka_clients

  const val kafka: String = "org.apache.kafka:kafka:" + Versions.kafka

  /**
   * https://kafka.apache.org
   */
  const val kafka_2_11: String = "org.apache.kafka:kafka_2.11:" + Versions.kafka_2_11

  const val log4j_: String = "org.apache.logging.log4j:log4j-:" + Versions.log4j_

  /**
   * https://logging.apache.org/log4j/2.x/
   */
  const val log4j_core: String = "org.apache.logging.log4j:log4j-core:" + Versions.log4j_core

  /**
   * https://logging.apache.org/log4j/2.x/
   */
  const val log4j_to_slf4j: String = "org.apache.logging.log4j:log4j-to-slf4j:" +
      Versions.log4j_to_slf4j

  /**
   * http://mesos.apache.org
   */
  const val mesos: String = "org.apache.mesos:mesos:" + Versions.mesos

  /**
   * http://nifi.apache.org
   */
  const val nifi_site_to_site_client: String = "org.apache.nifi:nifi-site-to-site-client:" +
      Versions.nifi_site_to_site_client

  /**
   * http://orc.apache.org
   */
  const val orc_core: String = "org.apache.orc:orc-core:" + Versions.orc_core

  /**
   * https://parquet.apache.org
   */
  const val parquet_avro: String = "org.apache.parquet:parquet-avro:" + Versions.org_apache_parquet

  /**
   * https://parquet.apache.org
   */
  const val parquet_hadoop: String = "org.apache.parquet:parquet-hadoop:" +
      Versions.org_apache_parquet

  /**
   * http://zookeeper.apache.org
   */
  const val zookeeper: String = "org.apache.zookeeper:zookeeper:" + Versions.zookeeper

  /**
   * http://software.clapper.org/grizzled-slf4j/
   */
  const val grizzled_slf4j_2_11: String = "org.clapper:grizzled-slf4j_2.11:" +
      Versions.grizzled_slf4j_2_11

  /**
   * http://janino-compiler.github.io/janino/
   */
  const val janino: String = "org.codehaus.janino:janino:" + Versions.janino

  /**
   * https://github.com/elastic/elasticsearch
   */
  const val elasticsearch_rest_high_level_client: String =
      "org.elasticsearch.client:elasticsearch-rest-high-level-client:" +
      Versions.org_elasticsearch_client

  /**
   * https://github.com/elastic/elasticsearch
   */
  const val transport: String = "org.elasticsearch.client:transport:" +
      Versions.org_elasticsearch_client

  /**
   * https://github.com/elastic/elasticsearch
   */
  const val transport_netty4_client: String = "org.elasticsearch.plugin:transport-netty4-client:" +
      Versions.transport_netty4_client

  /**
   * https://github.com/elastic/elasticsearch
   */
  const val elasticsearch: String = "org.elasticsearch:elasticsearch:" + Versions.elasticsearch

  /**
   * https://github.com/hamcrest/JavaHamcrest
   */
  const val hamcrest_all: String = "org.hamcrest:hamcrest-all:" + Versions.hamcrest_all

  /**
   * http://www.influxdb.org
   */
  const val influxdb_java: String = "org.influxdb:influxdb-java:" + Versions.influxdb_java

  /**
   * http://www.javassist.org/
   */
  const val javassist: String = "org.javassist:javassist:" + Versions.javassist

  const val jline_reader: String = "org.jline:jline-reader:" + Versions.org_jline

  const val jline_terminal: String = "org.jline:jline-terminal:" + Versions.org_jline

  /**
   * https://www.joda.org/${joda.artifactId}/
   */
  const val joda_convert: String = "org.joda:joda-convert:" + Versions.joda_convert

  /**
   * https://jsoup.org/
   */
  const val jsoup: String = "org.jsoup:jsoup:" + Versions.jsoup

  /**
   * https://github.com/lz4/lz4-java
   */
  const val lz4_java: String = "org.lz4:lz4-java:" + Versions.lz4_java

  /**
   * https://github.com/mockito/mockito
   */
  const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

  /**
   * http://www.powermock.org
   */
  const val powermock_api_mockito2: String = "org.powermock:powermock-api-mockito2:" +
      Versions.org_powermock

  /**
   * http://www.powermock.org
   */
  const val powermock_module_junit4: String = "org.powermock:powermock-module-junit4:" +
      Versions.org_powermock

  /**
   * https://projectlombok.org
   */
  const val lombok: String = "org.projectlombok:lombok:" + Versions.lombok

  /**
   * http://github.com/ronmamo/reflections
   */
  const val reflections: String = "org.reflections:reflections:" + Versions.reflections

  /**
   * https://www.scala-lang.org/
   */
  const val scala_compiler: String = "org.scala-lang:scala-compiler:" + Versions.org_scala_lang

  /**
   * https://www.scala-lang.org/
   */
  const val scala_library: String = "org.scala-lang:scala-library:" + Versions.org_scala_lang

  const val scala_r: String = "org.scala-lang:scala-r:" + Versions.org_scala_lang

  /**
   * https://www.scala-lang.org/
   */
  const val scala_reflect: String = "org.scala-lang:scala-reflect:" + Versions.org_scala_lang

  const val scalatest2_11: String = "org.scalatest:scalatest2.11:" + Versions.org_scalatest

  /**
   * http://www.artima.com/scalatest/
   */
  const val scalatest: String = "org.scalatest:scalatest:" + Versions.org_scalatest

  /**
   * http://www.scalatest.org
   */
  const val scalatest_2_11: String = "org.scalatest:scalatest_2.11:" + Versions.org_scalatest

  /**
   * http://moepii.sourceforge.net/
   */
  const val irclib: String = "org.schwering:irclib:" + Versions.irclib

  /**
   * http://www.slf4j.org
   */
  const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.org_slf4j

  /**
   * http://www.slf4j.org
   */
  const val slf4j_log4j12: String = "org.slf4j:slf4j-log4j12:" + Versions.org_slf4j

  /**
   * https://github.com/xerial/snappy-java
   */
  const val snappy_java: String = "org.xerial.snappy:snappy-java:" + Versions.snappy_java
}
