import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {

  const val baseScala: String = "2.11"

  const val zkclient: String = "0.7" // available: "0.11"

  const val aliyun_sdk_oss: String = "3.4.1" // available: "3.6.0"

  const val aws_java_sdk_core: String = "1.11.271" // available: "1.11.618"

  const val aws_java_sdk_dynamodb: String = "1.11.271" // available: "1.11.618"

  const val aws_java_sdk_kms: String = "1.11.271" // available: "1.11.618"

  const val aws_java_sdk_s3: String = "1.11.437" // available: "1.11.618"

  const val frocksdbjni: String = "5.17.2-artisans-1.0"

  const val com_datastax_cassandra: String = "3.0.0" // available: "4.0.0"

  const val kryo: String = "2.24.0"

  const val hadoop_apache2: String = "2.7.3-1" // available: "2.7.4-5"

  const val presto_hive: String = "0.187" // available: "0.224"

  const val oshi_core: String = "3.4.0" // available: "4.0.0"

  const val scopt_2_11: String = "3.5.0" // available: "3.7.1"

  const val wiremock: String = "2.19.0" // available: "2.24.1"

  const val google_cloud_pubsub: String = "1.62.0" // available: "1.88.0"

  const val jsr305: String = "1.3.9" // available: "3.0.2"

  const val guava: String = "18.0" // available: "28.0-jre"

  const val hiverunner: String = "4.0.0" // available: "4.1.0"

  const val unirest_java: String = "1.4.9"

  const val azure: String = "1.16.0" // available: "1.25.0"

  const val fenzo_core: String = "0.10.1" // available: "1.0.1"

  const val amqp_client: String = "4.2.0" // available: "5.7.3"

  const val docker_client: String = "8.11.7" // available: "8.16.0"

  const val okhttp: String = "3.7.0" // available: "4.1.0"

  const val chill2_11: String = "0.7.6"

  const val chill_2_11: String = "0.7.6" // available: "0.9.3"

  const val hbc_core: String = "2.2.0"

  const val com_typesafe_akka: String = "2.5.21" // available: "2.5.25"

  const val commons_cli: String = "1.3.1" // available: "1.4"

  const val commons_collections: String = "3.2.2" // available: "20040616"

  const val commons_io: String = "2.4" // available: "2.6"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val tpch: String = "0.10"

  const val kafka_schema_registry_client: String = "3.3.1" // available: "5.3.0"

  const val io_dropwizard_metrics: String = "3.1.5" // available: "4.1.0"

  const val netty: String = "3.10.6.Final"

  const val io_prometheus: String = "0.3.0" // available: "0.6.0"

  const val fastutil: String = "8.2.1" // available: "8.3.0"

  const val joda_time: String = "2.5" // available: "2.10.3"

  const val junit: String = "4.12"

  const val log4j: String = "1.2.17"

  const val pyrolite: String = "4.13" // available: "4.30"

  const val py4j: String = "0.10.8.1"

  const val avro: String = "1.8.2" // available: "1.9.0"

  const val avatica_core: String = "1.15.0"

  const val calcite_core: String = "1.20.0"

  const val cassandra_all: String = "2.2.5" // available: "3.11.4"

  const val commons_compress: String = "1.18"

  const val commons_lang3: String = "3.3.2" // available: "3.9"

  const val commons_math3: String = "3.5" // available: "3.6.1"

  const val org_apache_curator: String = "2.12.0" // available: "4.2.0"

  const val derby: String = "10.14.2.0" // available: "10.15.1.3"

  const val flink_shaded_asm_6: String = "6.2.1-7.0"

  const val flink_shaded_guava: String = "18.0-7.0"

  const val flink_shaded_hadoop_2: String = "2.4.1-7.0"

  const val flink_shaded_jackson_module_jsonschema: String = "2.9.8-7.0"

  const val flink_shaded_jackson: String = "2.9.8-7.0"

  const val flink_shaded_netty_tcnative_dynamic: String = "2.0.25.Final-7.0"

  const val flink_shaded_netty: String = "4.1.32.Final-7.0"

  const val hadoop_aliyun: String = "3.1.0" // available: "3.2.0"

  const val hadoop_aws: String = "3.1.0" // available: "3.2.0"

  const val hadoop_azure: String = "3.1.0" // available: "3.2.0"

  const val hadoop_client: String = "2.8.1" // available: "3.2.0"

  const val hadoop_common: String = "3.1.0" // available: "3.2.0"

  const val hadoop_hdfs: String = "2.4.1" // available: "3.2.0"

  const val hadoop_mapreduce_client_core: String = "2.7.5" // available: "3.2.0"

  const val hadoop_minicluster: String = "2.4.1" // available: "3.2.0"

  const val hadoop_minikdc: String = "2.7.2" // available: "3.2.0"

  const val hadoop_openstack: String = "2.8.1" // available: "3.2.0"

  const val hadoop_yarn_api: String = "2.4.1"

  const val hadoop_yarn_client: String = "2.4.1" // available: "3.2.0"

  const val org_apache_hbase: String = "1.4.3" // available: "2.2.0"

  const val hcatalog_core: String = "0.12.0"

  const val hive_hcatalog_core: String = "2.3.4" // available: "3.1.1"

  const val org_apache_hive: String = "2.3.4" // available: "3.1.1"

  const val kafka_clients: String = "2.2.0" // available: "5.3.0-ce"

  const val kafka: String = "2.2.0"

  const val kafka_2_11: String = "0.8.2.2" // available: "5.3.0-ce"

  const val log4j_: String = "2.7"

  const val log4j_core: String = "2.9.1" // available: "2.12.1"

  const val log4j_to_slf4j: String = "2.9.1" // available: "2.12.1"

  const val mesos: String = "1.0.1" // available: "1.8.1"

  const val nifi_site_to_site_client: String = "1.6.0" // available: "1.9.2"

  const val orc_core: String = "1.4.3" // available: "1.5.6"

  const val org_apache_parquet: String = "1.10.0" // available: "1.10.1"

  const val zookeeper: String = "3.4.10" // available: "3.5.5"

  const val grizzled_slf4j_2_11: String = "1.3.2" // available: "1.3.4"

  const val janino: String = "3.0.9" // available: "3.1.0"

  const val org_elasticsearch_client: String = "6.3.1" // available: "7.3.1"

  const val transport_netty4_client: String = "6.3.1" // available: "7.3.1"

  const val elasticsearch: String = "2.3.5" // available: "7.3.1"

  const val hamcrest_all: String = "1.3"

  const val influxdb_java: String = "2.14" // available: "2.15"

  const val javassist: String = "3.24.0-GA" // available: "3.25.0-GA"

  const val jcip_annotations: String = "1.0"

  const val org_jline: String = "3.9.0" // available: "3.12.1"

  const val joda_convert: String = "1.7" // available: "2.2.1"

  const val jsoup: String = "1.11.2" // available: "1.12.1"

  const val lz4_java: String = "1.5.0" // available: "1.6.0"

  const val mockito_core: String = "2.21.0" // available: "3.0.0"

  const val org_powermock: String = "2.0.2"

  const val lombok: String = "1.16.22" // available: "1.18.8"

  const val reflections: String = "0.9.8" // available: "0.9.11"

  const val org_scala_lang: String = "2.11.12" // available: "2.13.0"

  const val org_scalatest: String = "3.0.0"

  const val irclib: String = "1.10"

  const val org_slf4j: String = "1.7.15" // available: "1.7.28"

  const val snappy_java: String = "1.1.4" // available: "1.1.7.3"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6"

  const val gradleCurrentVersion: String = "5.5.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
